### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by peternewman** [rbalykov/cdmx#2]
You somewhat skirted round my issue (or perhaps I wasn't clear enough) and then you've deleted the original issue.

"github just gives a choice on repo creation"

I'm aware of that, it doesn't mean you need to pick private though.

Is this a closed source project? What's the licence for it? There isn't currently a licence file.

**Comment by peternewman** [comment]
Apologies, I see it's GPL in the top of the C file, although I'm a bit unclear why it's a private project still and there's still no licence file.

**Comment by rbalykov** [comment]
> Apologies, I see it's GPL in the top of the C file, although I'm a bit unclear why it's a private project still and there's still no licence file.

1) It still doesn't work, don't want bring it to audience
2) newbie to opensource, never cared of licences

**Comment by peternewman** [comment]
> 1. It still doesn't work, don't want bring it to audience

Fair point, although someone else may have the fix!

> 2. newbie to opensource, never cared of licences

I'm not too worried about the licences per se, but I do feel differently helping with closed versus open source software, although it sounds like this will become the latter if it can be made to work.

In terms of assisting with that, see my comments in https://github.com/rbalykov/cdmx/issues/1#issuecomment-916619588
